# Customize site navigation
nav:
- name: 首页
  url: /
- name: 归档
  url: /archives.html
- name: 标签
  url: /tags.html
- name: 关于
  url: /about.html

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- icon: github
  link: https://github.com/daotin/daotin.github.io
- icon: false
  link: https://zhihu.com/people/daotin
  
# Customize site text
prev: 上一页
next: 下一页

prev_page: 上一页
next_page: 下一页

search_tip: Press enter to search
searching: Searching

blog: Blog

read_more: Read More

edit: edit
